apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hello-world-ingress
  namespace: ingress-basic
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: poi-service
          servicePort: 80
        path: /api/poi(/|$)(.*)
      - backend:
          serviceName: trips-service
          servicePort: 80
        path: /api/trips(/|$)(.*)
      - backend:
          serviceName: user-java-service
          servicePort: 80
        path: /api/user-java(/|$)(.*)
      - backend:
          serviceName: userprofile-service
          servicePort: 80
        path: /api/userprofile(/|$)(.*)
      - backend:
          serviceName: tripviewer-service
          servicePort: 80
        path: /(.*)