apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer-deployment
  labels:
    app: tripviewer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
      - name: tripviewer
        image: registrycyb9188.azurecr.io/tripinsights/tripviewer:1.0
        resources:
            limits:
              cpu: 250m
              memory: 256Mi
        ports:
        - containerPort: 80