apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer-deployment
  labels:
    app: tripviewer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
        version: '1.0'
    spec:
      containers:
      - name: tripviewer
        image: registrycyb9188.azurecr.io/tripviewer2:1.0
        env:
          - name: TRIPS_API_ENDPOINT
            value: http://trips-service.api.svc.cluster.local:3000
          - name: USERPROFILE_API_ENDPOINT
            value: http://userprofile-service.api.svc.cluster.local:80
          - name: WCF_ENDPOINT
            value: http://wcf-service.default.svc.cluster.local:80
        resources:
            limits:
              cpu: 250m
              memory: 256Mi
        ports:
        - containerPort: 80