apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi-deployment
  labels:
    app: poi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - name: poi
        image: registrycyb9188.azurecr.io/tripinsights/poi:1.0
        resources:
            limits:
              cpu: 500m
              memory: 256Mi
        ports:
        - containerPort: 80